Bug Tracker/Bug Tracker/Models/Attachment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bug_Tracker.Models
{
    public class Attachment
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public string Body { get; set; }
        [DisplayFormat(DataFormatString = "{0:M/d/yyyy h:mm tt}")]
        public DateTimeOffset Created { get; set; }
        public string AuthorUserId { get; set; }
        public string FileUrl { get; set; }
        public string FileDisplayName { get; set; }

        public virtual ApplicationUser AuthorUser { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}

Bug Tracker/Bug Tracker/Controllers/AttachmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bug_Tracker.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Threading.Tasks;
using System.Configuration;

namespace Bug_Tracker.Controllers
{
    public class AttachmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Attachments
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var attachments = db.Attachments.Include(a => a.AuthorUser).Include(a => a.Ticket);
            return View(attachments.ToList());
        }

        // GET: Attachments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attachment attachment = db.Attachments.Find(id);
            if (attachment == null)
            {
                return HttpNotFound();
            }
            return View(attachment);
        }

        // GET: Attachments/Create
        public ActionResult Create()
        {
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title");
            return View();
        }

        // POST: Attachments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Create([Bind(Include = "Id,TicketId,Body,Created,AuthorUserId,FileUrl,FileDisplayName")] Attachment attachment, HttpPostedFileBase file)
        {
            //if (file != null && file.ContentLength > 0)
            //{
            // Only allow certain file types
            //var ext = Path.GetExtension(file.FileName).ToLower();
            //if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp" && ext != ".pdf" && ext != ".doc" && ext != ".docx" && ext != ".xls" && ext != ".xlt" && ext != ".ppt" && ext != ".pps")
            //{
            // Error Message???
            //ModelState.AddModelError("file", "Invalid Format.");
            //    }
            //}
            if (ModelState.IsValid)
            {
                if (attachment != null)
                {
                    // Relative server path
                    var filePath = "/Uploads/";
                    // Path on physical drive on server
                    var absPath = Server.MapPath("~" + filePath);
                    // File url for relative path
                    attachment.FileUrl = filePath + file.FileName;
                    // Save file
                    file.SaveAs(Path.Combine(absPath, file.FileName));
                }

                var history = new History
                {
                    ChangeDate = new DateTimeOffset(DateTime.Now),
                    TicketId = attachment.TicketId,
                    UserId = User.Identity.GetUserId(),
                    Property = "A user attached the file: ",
                    NewValue = attachment.FileDisplayName
                };
                db.Histories.Add(history);

                await Notify(attachment.TicketId, history);

                attachment.AuthorUserId = User.Identity.GetUserId();
                attachment.Created = DateTimeOffset.Now;
                db.Attachments.Add(attachment);
                db.SaveChanges();
                var thisTicket = db.Tickets.Find(attachment.TicketId);
                if (thisTicket != null)
                {
                    return RedirectToAction("Edit", "Tickets", new { id = thisTicket.Id });
                }
            }
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", attachment.AuthorUserId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", attachment.TicketId);
            return RedirectToAction("Edit", "Tickets", new { id = ViewBag.TicketId });
        }

        // POST: Ticket/Notifications
        public async Task Notify(int ticketId, History history)
        {
            var db = new ApplicationDbContext();
            var ticket = db.Tickets.Find(ticketId);
            //var ticket = db.Tickets.Include("Project").FirstOrDefault(t => t.Id == ticketId);
            var displayName = db.Users.Find(history.UserId).DisplayName;
            var emailService = new PersonalEmail();

            // If the ticket is already assigned to a user and the user is not being changed
            if (ticket.AssignedToUserId != null && history.Property != "assigned user")
            {
                await emailService.SendAsync(new System.Net.Mail.MailMessage(ConfigurationManager.AppSettings["username"], ticket.AssignedToUser.UserName)
                {
                    Subject = "A ticket that you are assigned to has a new attachment.",
                    Body = ticket.AssignedToUser.FirstName + ", </p>" + displayName + " has added the attachment <i>" + history.NewValue + "</i> to ticket <i>" + ticket.Title + "</i>.",
                    IsBodyHtml = true
                });
            }
        }

        // GET: Attachments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attachment attachment = db.Attachments.Find(id);
            if (attachment == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", attachment.AuthorUserId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", attachment.TicketId);
            return View(attachment);
        }

        // POST: Attachments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TicketId,Body,Created,AuthorUserId,FileUrl,FileDisplayName")] Attachment attachment)
        {
            if (ModelState.IsValid)
            {
                var history = new History
                {
                    ChangeDate = new DateTimeOffset(DateTime.Now),
                    TicketId = attachment.TicketId,
                    UserId = User.Identity.GetUserId(),
                    Property = "A user updated the attached the file: ",
                    NewValue = attachment.FileDisplayName
                };
                db.Histories.Add(history);

                //if (attachment != null)
                //{
                //    // Relative server path
                //    var filePath = "/Uploads/";
                //    // Path on physical drive on server
                //    var absPath = Server.MapPath("~" + filePath);
                //    // File url for relative path
                //    attachment.FileUrl = filePath + file.FileName;
                //    // Save file
                //    file.SaveAs(Path.Combine(absPath, file.FileName));
                //}

                attachment.AuthorUserId = User.Identity.GetUserId();
                attachment.Created = DateTimeOffset.Now;
                db.Attachments.Add(attachment);
                db.Entry(attachment).State = EntityState.Modified;
                db.SaveChanges();
                var thisTicket = db.Tickets.Find(attachment.TicketId);
                if (thisTicket != null)
                {
                    return RedirectToAction("Edit", "Tickets", new { id = thisTicket.Id });
                }
            }
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", attachment.AuthorUserId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", attachment.TicketId);
            return View(attachment);
        }

        // GET: Attachments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attachment attachment = db.Attachments.Find(id);
            if (attachment == null)
            {
                return HttpNotFound();
            }
            return View(attachment);
        }

        // POST: Attachments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Attachment attachment = db.Attachments.Find(id);

            var history = new History
            {
                ChangeDate = new DateTimeOffset(DateTime.Now),
                TicketId = attachment.TicketId,
                UserId = User.Identity.GetUserId(),
                Property = "A user removed the file: ",
                NewValue = attachment.FileDisplayName
            };
            db.Histories.Add(history);

            db.Attachments.Remove(attachment);
            db.SaveChanges();
            var thisTicket = db.Tickets.Find(attachment.TicketId);
            if (thisTicket != null)
            {
                return RedirectToAction("Edit", "Tickets", new { id = thisTicket.Id });
            }
            return View(attachment);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bug Tracker/Bug Tracker/Views/Attachments/Create.cshtml
@model Bug_Tracker.Models.Attachment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attachment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TicketId, "TicketId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorUserId, "AuthorUserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorUserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileDisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileDisplayName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileDisplayName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Bug Tracker/Bug Tracker/Views/Attachments/Delete.cshtml
@model Bug_Tracker.Models.Attachment

@{
    ViewBag.Title = "Delete";
}
<h3>Are you sure you want to delete this attachment?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            File Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileDisplayName)
        </dd>

        <dt>
            Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            Uploaded by
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorUser.DisplayName)
        </dd>

        <dt>
            On Ticket
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ticket.Title)
        </dd>

        <dt>
            Uploaded on
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            File url
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileUrl)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-1 col-md-11">
                <ul class="list-inline">
                    <li>
                        <a href="@Url.Action("Edit", "Tickets",  new { id = Model.TicketId })" class="btn btn-warning"> <i class="fa fa-ban"></i> Cancel</a>
                    </li>
                    <li>
                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                    </li>
                </ul>
            </div>
        </div>
    }
</div>

Bug Tracker/Bug Tracker/Views/Attachments/Details.cshtml
@model Bug_Tracker.Models.Attachment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Attachment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AuthorUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ticket.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileDisplayName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileDisplayName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Bug Tracker/Bug Tracker/Views/Attachments/Edit.cshtml
@model Bug_Tracker.Models.Attachment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit your attachment: <i>@Model.FileDisplayName</i></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
        @Html.HiddenFor(model => model.TicketId)
        @Html.HiddenFor(model => model.AuthorUserId)
        @Html.HiddenFor(model => model.FileUrl)

        @*<div class="form-group">
            @Html.LabelFor(model => model.TicketId, "TicketId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.AuthorUserId, "AuthorUserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorUserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.FileUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileUrl, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FileDisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileDisplayName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileDisplayName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <ul class="list-inline">
                    <li>
                        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save</button>
                    </li>
                    <li>
                        <a href="@Url.Action("Edit", "Tickets",  new { id = Model.TicketId })" class="btn btn-primary"> <i class="fa fa-arrow-left"></i> Back to Ticket</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Delete", "Attachments",  new { id = Model.Id })" class="btn btn-danger"> <i class="fa fa-trash"></i> Delete Attachment</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
}

Bug Tracker/Bug Tracker/Views/Attachments/Index.cshtml
@model IEnumerable<Bug_Tracker.Models.Attachment>

@{
    ViewBag.Title = "Index";
}

@if (User.IsInRole("Admin"))
{
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                All Attachments
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-attach">
                        <thead>
                            <tr>
                                <th class="col-sm-2">File Name <i class="fa fa-sort"></i></th>
                                <th class="col-sm-2">Description <i class="fa fa-sort"></i></th>
                                <th class="col-sm-2">Uploaded by <i class="fa fa-sort"></i></th>
                                <th class="col-sm-2">On Ticket <i class="fa fa-sort"></i></th>
                                <th class="col-sm-1">Uploaded on <i class="fa fa-sort"></i></th>
                                <th class="col-sm-2">File url <i class="fa fa-sort"></i></th>
                                <th class="col-sm-1"></th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model.OrderBy(a => a.FileDisplayName))
                            {
                                <tr>
                                    <td class="col-sm-2">
                                        @Html.DisplayFor(modelItem => item.FileDisplayName)
                                    </td>
                                    <td class="col-sm-2">
                                        @Html.DisplayFor(modelItem => item.Body)
                                    </td>
                                    <td class="col-sm-2">
                                        @Html.DisplayFor(modelItem => item.AuthorUser.UserName)
                                    </td>
                                    <td class="col-sm-2">
                                        @Html.DisplayFor(modelItem => item.Ticket.Title)
                                    </td>
                                    <td class="col-sm-1">
                                        @Html.DisplayFor(modelItem => item.Created)
                                    </td>
                                    <td class="col-sm-2">
                                        @Html.DisplayFor(modelItem => item.FileUrl)
                                    </td>
                                    <td class="col-sm-1">
                                        <a href='@Url.Action("Edit", "Attachments", new { id = item.Id })' class="btn btn-block btn-sm btn-stack btn-warning"><i class="fa fa-pencil"></i> Edit</a>
                                        <a href='@Url.Action("Delete", "Attachments", new { id = item.Id })' class="btn btn-block btn-sm btn-stack btn-danger"><i class="fa fa-trash"></i> Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
}

<script src="~/Template/assets/js/jquery-1.10.2.js"></script>
<!-- Bootstrap Js -->
<script src="~/Template/assets/js/bootstrap.min.js"></script>
<!-- Metis Menu Js -->
<script src="~/assets/js/jquery.metisMenu.js"></script>
<!-- DATA TABLE SCRIPTS -->
<script src="~/Template/assets/js/dataTables/jquery.dataTables.js"></script>
<script src="~/Template/assets/js/dataTables/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#dataTables-attach').dataTable();
    });
</script>
<script src="~/Template/assets/js/custom-scripts.js"></script>