Personal MVC site/Personal MVC site/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Personal_MVC_site.Models;
using Personal_MVC_site.Helpers;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace Personal_MVC_site.Controllers
{
    [RequireHttps]
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts (User Index)
        public ActionResult Index(int? page, string searchStr)
        {
            ViewBag.Message = "Blog";
            ViewBag.Search = searchStr;
            var blogList = IndexSearch(searchStr);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var posts = db.Posts.OrderBy(p => p.Created).ToPagedList(pageNumber, pageSize);
            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        public IQueryable<BlogPost> IndexSearch(string searchStr)
        {
            IQueryable<BlogPost> result = null;
            if (searchStr != null)
            {
                result = db.Posts.AsQueryable();
                result = result.Where(p => p.Title.Contains(searchStr) || p.Body.Contains(searchStr) || p.Comments.Any(c => c.Body.Contains(searchStr) || c.Author.FirstName.Contains(searchStr) || c.Author.LastName.Contains(searchStr) || c.Author.DisplayName.Contains(searchStr) || c.Author.Email.Contains(searchStr)));
            }
            else
            {
                result = db.Posts.AsQueryable();
            }
            return result.OrderByDescending(p => p.Created);
        }

        // GET: BlogPosts (IndexAdmin)
        [Authorize(Roles = "Admin")]
        public ActionResult IndexAdmin(int? page, string searchStrAdmin)
        {
            ViewBag.Search = searchStrAdmin;
            var blogList = AdminSearch(searchStrAdmin);
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            var posts = db.Posts.OrderBy(p => p.Created).ToPagedList(pageNumber, pageSize);
            return View(blogList.ToPagedList(pageNumber, pageSize));
        }
        public IQueryable<BlogPost> AdminSearch(string searchStrAdmin)
        {
            IQueryable<BlogPost> result = null;
            if (searchStrAdmin != null)
            {
                result = db.Posts.AsQueryable();
                result = result.Where(p => p.Title.Contains(searchStrAdmin) || p.Body.Contains(searchStrAdmin) || p.Comments.Any(c => c.Body.Contains(searchStrAdmin) || c.Author.FirstName.Contains(searchStrAdmin) || c.Author.LastName.Contains(searchStrAdmin) || c.Author.DisplayName.Contains(searchStrAdmin) || c.Author.Email.Contains(searchStrAdmin)));
            }
            else
            {
                result = db.Posts.AsQueryable();
            }
            return result.OrderByDescending(p => p.Created);
        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == Slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Details (NEW)
        [Authorize(Roles = "Admin")]
        public ActionResult DetailsAdmin(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == Slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,Title,Body,MediaURL")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                // Check the file name to make sure its an image
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                {
                    ModelState.AddModelError("image", "Invalid Format.");
                }
            }
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    // Relative server path
                    var filePath = "/img/Uploads/";
                    // Path on physical drive on server
                    var absPath = Server.MapPath("~" + filePath);
                    // Media url for relative path
                    blogPost.MediaURL = filePath + image.FileName;
                    // Save image
                    image.SaveAs(Path.Combine(absPath, image.FileName));
                }
                var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blogPost);
                }
                if(db.Posts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }
                blogPost.Slug = Slug;
                blogPost.Created = DateTimeOffset.Now;
                db.Posts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == Slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,Created,Title,Body,MediaURL")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                // Check the file name to make sure its an image
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                {
                    ModelState.AddModelError("image", "Invalid Format.");
                }
            }
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    // Relative server path
                    var filePath = "/img/Uploads/";
                    // Path on physical drive on server
                    var absPath = Server.MapPath("~" + filePath);
                    // Media url for relative path
                    blogPost.MediaURL = filePath + image.FileName;
                    // Save image
                    image.SaveAs(Path.Combine(absPath, image.FileName));
                }
                var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blogPost);
                }
                var editSlug = StringUtilities.URLFriendly(blogPost.Title);
                if (db.Posts.Any((p => p.Title == blogPost.Title && p.Id != blogPost.Id)))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }
                blogPost.Slug = editSlug;
                db.Entry(blogPost).State = EntityState.Modified;
                blogPost.Updated = DateTimeOffset.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: BlogPosts/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.Posts.Find(id);
            db.Posts.Remove(blogPost);
            db.SaveChanges();

Personal MVC site/Personal MVC site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sam Gray | Web Developer @ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap.css")
    @*@Styles.Render("~/Content/css")*@
    @Styles.Render("~/Content/creative.min.css")
    @Styles.Render("~/Content/grayscale.min.css")
    @Styles.Render("~/Content/PagedList.css")
    @*@Scripts.Render("~/bundles/modernizr")*@
    @Styles.Render("https://fonts.googleapis.com/css?family=Kreon:300,400")
    @Styles.Render("https://fonts.googleapis.com/css?family=Montserrat:400,700")
    @Styles.Render("https://fonts.googleapis.com/css?family=Vast+Shadow")
    @Styles.Render("https://fonts.googleapis.com/css?family=Roboto+Slab:700")

    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.eot")
    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.svg")
    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.ttf")
    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.woff")

    @Styles.Render("~/fonts/font-awesome/css/font-awesome.min.css")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.eot")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.svg")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.ttf")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.woff")
    @Styles.Render("~/fonts/font-awesome/fonts/FontAwesome.otf")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.woff2")
    @Styles.Render("~/Content/lightbox.css")
</head>

<body>
    @RenderBody()
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Samuel Gray @DateTime.Now.Year</p>
        </div>
    </footer>

    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js")
    @Scripts.Render("~/Scripts/grayscale.min.js")
    @Scripts.Render("~/Scripts/creative.min.js")
    @Scripts.Render("~/Scripts/lightbox.js")
    @RenderSection("scripts", required: false)
    </body>
</html>

Personal MVC site/Personal MVC site/Views/Shared/_LayoutBlog.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sam Gray | Web Developer @ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap.css")
    @*@Styles.Render("~/Content/css")*@
    @Styles.Render("~/Content/creative.min.css")
    @Styles.Render("~/Content/grayscale.min.css")
    @Styles.Render("~/Content/PagedList.css")
    @*@Scripts.Render("~/bundles/modernizr")*@
    @Styles.Render("https://fonts.googleapis.com/css?family=Kreon:300,400")
    @Styles.Render("https://fonts.googleapis.com/css?family=Montserrat:400,700")
    @Styles.Render("https://fonts.googleapis.com/css?family=Vast+Shadow")
    @Styles.Render("https://fonts.googleapis.com/css?family=Roboto+Slab:700")

    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.eot")
    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.svg")
    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.ttf")
    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.woff")

    @Styles.Render("~/fonts/font-awesome/css/font-awesome.min.css")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.eot")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.svg")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.ttf")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.woff")
    @Styles.Render("~/fonts/font-awesome/fonts/FontAwesome.otf")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.woff2")
    @Styles.Render("~/Content/lightbox.css")
</head>

<body>
    <!-- Navigation -->
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a href='@Url.Action("Index", "Home")#page-top' class="navbar-brand page-scroll top-nav">
                    <span class="light">Sam</span> Gray
                </a>
                @*</a>*@
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href='@Url.Action("Index", "Home")#page-top' class="page-scroll top-nav"></a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index", "Home")#about' class="page-scroll top-nav">About</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index", "Home")#resume' class="page-scroll top-nav">Resumé</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index", "Home")#portfolio' class="page-scroll top-nav">Portfolio</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index", "Home")#contact' class="page-scroll top-nav">Contact</a>
                    </li>
                    <li>
                        @if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                            {
                                @Html.AntiForgeryToken()
                                <a href="javascript:document.getElementById('logoutForm').submit()" class="page-scroll top-nav">Log off</a>
                            }
                            @*<a href='@Url.Action("LogOff", "Account")' class="page-scroll top-nav">Log Out</a>*@
                        }
                        else
                        {
                            <a href='@Url.Action("Login", "Account")' class="page-scroll top-nav">Log In</a>
                        }
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>
    @RenderBody()
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Samuel Gray @DateTime.Now.Year</p>
        </div>
    </footer>
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js")
    @Scripts.Render("~/Scripts/grayscale.min.js")
    @Scripts.Render("~/Scripts/creative.min.js")
    @Scripts.Render("~/Scripts/lightbox.js")
    @RenderSection("scripts", required: false)
</body>
</html>

Personal MVC site/Personal MVC site/Views/Shared/_LayoutSecondary.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sam Gray | Web Developer @ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap.css")
    @*@Styles.Render("~/Content/css")*@
    @Styles.Render("~/Content/creative.min.css")
    @Styles.Render("~/Content/grayscale.min.css")
    @Styles.Render("~/Content/PagedList.css")
    @*@Scripts.Render("~/bundles/modernizr")*@
    @Styles.Render("https://fonts.googleapis.com/css?family=Kreon:300,400")
    @Styles.Render("https://fonts.googleapis.com/css?family=Montserrat:400,700")
    @Styles.Render("https://fonts.googleapis.com/css?family=Vast+Shadow")
    @Styles.Render("https://fonts.googleapis.com/css?family=Roboto+Slab:700")

    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.eot")
    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.svg")
    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.ttf")
    @Styles.Render("~/fonts/bootstrap/fonts/glyphicons-halflings-regular.woff")

    @Styles.Render("~/fonts/font-awesome/css/font-awesome.min.css")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.eot")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.svg")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.ttf")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.woff")
    @Styles.Render("~/fonts/font-awesome/fonts/FontAwesome.otf")
    @Styles.Render("~/fonts/font-awesome/fonts/fontawesome-webfont.woff2")
    @Styles.Render("~/Content/lightbox.css")
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a href='@Url.Action("Index", "Home")#page-top' class="navbar-brand page-scroll top-nav">
                    <span class="light">Sam</span> Gray
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href='@Url.Action("Index", "Home")#page-top' class="page-scroll top-nav"></a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index", "Home")#about' class="page-scroll top-nav">About</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index", "Home")#resume' class="page-scroll top-nav">Resumé</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index", "Home")#portfolio' class="page-scroll top-nav">Portfolio</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index", "Home")#contact' class="page-scroll top-nav">Contact</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Blog", "BlogPosts")' class="page-scroll top-nav">Blog</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>
    @RenderBody()
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Samuel Gray @DateTime.Now.Year</p>
        </div>
    </footer>
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js")
    @Scripts.Render("~/Scripts/grayscale.min.js")
    @Scripts.Render("~/Scripts/creative.min.js")
    @Scripts.Render("~/Scripts/lightbox.js")
    @RenderSection("scripts", required: false)
</body>
</html>