Bug Tracker/Bug Tracker/Models/Helpers/AssignHelper.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bug_Tracker.Models
{
    public class AssignHelper
    {
        private ApplicationDbContext db;

        public AssignHelper(ApplicationDbContext context)
        {
            //this.userManager = new UserManager<ApplicationUser>(
            //    new UserStore<ApplicationUser>(context));
            //this.roleManager = new RoleManager<IdentityRole>(
            //    new RoleStore<IdentityRole>(context));
            this.db = context;
        }

        public bool IsProjectOnUser(int projectId, string userId)
        {
            var project = db.Projects.Find(projectId);
            var userCheck = project.Users.Any(p => p.Id == userId);
            return (userCheck);
        }

        //public string GetUserInRole(string userId)
        //{
        //    return userManager.GetRoles(userId).First();
        //}

        //public IList<string> ListAssignedUsers(int projectId)
        public ICollection<ApplicationUser> ListAssignedUsers(int projectId)
        {
            Project project = db.Projects.Find(projectId);
            var userList = project.Users.ToList();
            return (userList);
        }

        public bool AddProjectToUser(int projectId, string userId)
        {
            Project project = db.Projects.Find(projectId);
            ApplicationUser user = db.Users.Find(userId);

            project.Users.Add(user);
            
            try
            {
                var userAdded = db.SaveChanges();

                if (userAdded != 0)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch
            {
                return false;
            }            

            //var roles = userManager.GetRoles(userId);
            //foreach(var role in roles)
            //{
            //    RemoveUserFromRole(userId, role);
            //}
            //var result = userManager.AddToRole(projectId, userId);
            //return result.Succeeded;
        }

        public bool RemoveProjectFromUser(int projectId, string userId)
        {
            Project project = db.Projects.Find(projectId);
            ApplicationUser user = db.Users.Find(userId);

            var result = project.Users.Remove(user);

            try
            {
                var userRemoved = db.SaveChanges();

                if (userRemoved != 0)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch
            {
                return false;
            }

            //var result = userManager.RemoveFromRole(projectId, userId);
            //return result.Succeeded;
        }

        //public bool AddTicketToUser(int ticketId, string userId)
        //{
        //    Ticket ticket = db.Tickets.Find(ticketId);
        //    ApplicationUser user = db.Users.Find(userId);

        //    ticket.AssignedToUserId.Add

        //    try
        //    {
        //        var userAdded = db.SaveChanges();

        //        if (userAdded != 0)
        //        {
        //            return true;
        //        }
        //        else
        //        {
        //            return false;
        //        }
        //    }
        //    catch
        //    {
        //        return false;
        //    }

        //    //var roles = userManager.GetRoles(userId);
        //    //foreach(var role in roles)
        //    //{
        //    //    RemoveUserFromRole(userId, role);
        //    //}
        //    //var result = userManager.AddToRole(projectId, userId);
        //    //return result.Succeeded;
        //}

        //NEEDED?
        //public IList<ApplicationUser> UsersInRole(string roleName)
        //{
        //    var userIDs = roleManager.FindByName(roleName).Users.Select(r => r.UserId);
        //    return userManager.Users.Where(u => userIDs.Contains(u.Id)).ToList();
        //    //Select(u => new UserDropDownViewModel { Id = u.Id, Name = u.DisplayName }).
        //}

        //NEEDED?
        //public IList<ApplicationUser> UsersNotInRole(string roleName)
        //{
        //    var userIDs = System.Web.Security.Roles.GetUsersInRole(roleName);
        //    return userManager.Users.Where(u => !userIDs.Contains(u.Id)).ToList();
        //    //Select(u => new UserDropDownViewModel { Id = u.Id, Name = u.DisplayName }).
        //}

        //public IList<string> ListUserRoles(string userId)
        //{
        //    return manager.GetRoles(userId);
        //}

        //public bool AddUserToRole(string userId, string roleName)
        //{
        //    var result = manager.AddToRole(userId, roleName);
        //    return result.Succeeded;
        //}

        //public bool RemoveUserFromRole(string userId, string roleName)
        //{
        //    var result = manager.RemoveUserFromRole(string userId, string roleName);
        //    return result.Succeeded;
        //}
    }
}

Bug Tracker/Bug Tracker/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bug_Tracker.Models
{
    public class Ticket
    {
        public Ticket()
        {
            this.Comments = new HashSet<Comment>();
            this.Attachments = new HashSet<Attachment>();
        }
        public int Id { get; set; }
        public string Title { get; set; }
        [Required]
        public string Body { get; set; }
        [DisplayFormat(DataFormatString = "{0:M/d/yyyy h:mm tt}")]
        public DateTimeOffset Created { get; set; }
        [DisplayFormat(DataFormatString = "{0:M/d/yyyy h:mm tt}")]
        public DateTimeOffset? Updated { get; set; }
        public int ProjectId { get; set; }
        public int TypeId { get; set; }
        public int PriorityId { get; set; }
        public int StatusId { get; set; }

        public string AuthorUserId { get; set; }
        public string AssignedToUserId { get; set; }

        public virtual Bug_Tracker.Models.Type Type { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }

        public virtual ApplicationUser AuthorUser { get; set; }
        public virtual ApplicationUser AssignedToUser { get; set; }
        public virtual Project Project { get; set; }

        public bool Deleted { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}

Bug Tracker/Bug Tracker/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bug_Tracker.Models;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Net.Mail;
using System.Configuration;

namespace Bug_Tracker.Controllers
{
    public class TicketsController : Controller
    {
        // GET: Tickets
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index(DashboardViewModel model)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            var userId = User.Identity.GetUserId();

            List<Project> relevantProjects = new List<Project>();
            List<Project> irrelevantProjects = new List<Project>();
            List<Ticket> relevantTickets = new List<Ticket>();
            List<Ticket> allTickets = new List<Ticket>();

            foreach (var project in db.Projects.ToList())
            {
                bool relevantProjectflag = false;

                foreach (var ticket in project.Tickets)
                {
                    allTickets.Add(ticket);
                }

                // Find Projects that users are assigned to and mark them Relevant
                foreach (var projectUser in project.Users)
                {
                    if (userId == projectUser.Id)
                    {
                        relevantProjectflag = true;
                    }
                }

                // Filter tickets ONLY for projects that are assigned to users
                // Find tickets ON Projects that are assigned to the PM
                // Find tickets that are assigned to Devs and created by Subs
                if (relevantProjectflag)
                {
                    relevantProjects.Add(project);

                    foreach (var ticket in project.Tickets)
                    {
                        if (User.IsInRole("Project Manager")
                        || ((User.IsInRole("Developer") && userId == ticket.AssignedToUserId) || User.IsInRole("Developer") && userId == ticket.AuthorUserId) || (User.IsInRole("Submitter") && userId == ticket.AuthorUserId))
                        {
                            relevantTickets.Add(ticket);
                        }
                    }
                }

                // Filter tickets ONLY for projects that are NOT assigned to users
                // Find tickets that were created by the PM
                else
                {
                    if (User.IsInRole("Project Manager"))
                    {
                        irrelevantProjects.Add(project);
                        foreach (var ticket in project.Tickets)
                        {
                            if (User.IsInRole("Project Manager") && userId == ticket.AuthorUserId)
                            {
                                relevantTickets.Add(ticket);
                            }
                        }
                    }
                }
            }
            model.RelevantProjects = relevantProjects;
            model.RelevantTickets = relevantTickets;

            if (User.IsInRole("Admin"))
            {
                model.AllTickets = allTickets;
            }

            return View(model);
        }

    // GET: Tickets/Details/5
    public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Tickets/Create
        public ActionResult Create(int id)
        {
            ViewBag.AssignedToUserId = new SelectList(db.Users, "Id", "FirstName");
            //ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.PriorityId = new SelectList(db.Priority, "Id", "Name");
            ViewBag.ProjectId = id;
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name");
            ViewBag.TypeId = new SelectList(db.Types, "Id", "Name");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Body,Created,Updated,ProjectId,TypeId,PriorityId,StatusId,AssignedToUserId")] Ticket ticket, int projectId)
        {
            if (ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();
                ticket.AuthorUserId = userId;
                ticket.ProjectId = projectId;
                ticket.Created = DateTimeOffset.Now;
                ticket.StatusId = 1;
                ticket.PriorityId = 5;
                db.Tickets.Add(ticket);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.AssignedToUserId = new SelectList(db.Users, "Id", "FirstName", ticket.AssignedToUserId);
            //ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", ticket.AuthorUserId);
            ViewBag.PriorityId = new SelectList(db.Priority, "Id", "Name", ticket.PriorityId);
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Title", ticket.ProjectId);
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name", ticket.StatusId);
            ViewBag.TypeId = new SelectList(db.Types, "Id", "Name", ticket.TypeId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            ApplicationDbContext context = new ApplicationDbContext();
            Project project = db.Projects.Find(ticket.ProjectId);
            var projectUsers = context.Users.Where(u => u.Projects.Any(p => p.Title == project.Title));
            var role = context.Roles.SingleOrDefault(u => u.Name == "Developer");
            var usersInRole = context.Users.Where(u => u.Roles.Any(r => (r.RoleId == role.Id)));
            var displayUsers = usersInRole.Where(u => u.Projects.Any(p => (p.Title == project.Title)));
            var removeUser = db.Users.Where(u => (u.DisplayName != "N/A" && u.DisplayName != "(Remove Assigned User)"));

            ViewBag.AssignedToUserId = new SelectList(displayUsers, "Id", "FirstName", ticket.AssignedToUserId);
            //ViewBag.AssignedToUserId = new SelectList(db.Users, "Id", "FirstName", ticket.AssignedToUserId);
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", ticket.AuthorUserId);
            ViewBag.PriorityId = new SelectList(db.Priority, "Id", "Name", ticket.PriorityId);
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Title", ticket.ProjectId);
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name", ticket.StatusId);
            ViewBag.TypeId = new SelectList(db.Types, "Id", "Name", ticket.TypeId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Body,Created,Updated,ProjectId,TypeId,PriorityId,Status,StatusId,AuthorUserId,AssignedToUserId")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                if (ticket.StatusId == 6)
                {
                    ticket.Deleted = true;
                }
                if (ticket.AssignedToUserId != null && ticket.StatusId < 2)
                {
                    ticket.StatusId = 2;
                }
                Ticket oldTicket = new ApplicationDbContext().Tickets.Find(ticket.Id);
                if (oldTicket.AssignedToUserId != ticket.AssignedToUserId)
                {
                    var history = new History
                    {
                        ChangeDate = new DateTimeOffset(DateTime.Now),
                        TicketId = ticket.Id,
                        UserId = User.Identity.GetUserId(),
                        Property = "The assigned user has been changed to",
                        NewValue = db.Users.Find(ticket.AssignedToUserId).FirstName,
                    };
                    db.Histories.Add(history);

                    ticket.Updated = DateTimeOffset.Now;
                    db.Entry(ticket).State = EntityState.Modified;
                    db.SaveChanges();

                    await Notify(ticket.Id, history);
                }

                    if (oldTicket.StatusId != ticket.StatusId)
                    {
                        var history = new History
                        {
                            ChangeDate = new DateTimeOffset(DateTime.Now),
                            TicketId = ticket.Id,
                            UserId = User.Identity.GetUserId(),
                            Property = "The status has been set to",
                            OldValue = oldTicket.Status.Name,
                            NewValue = db.Statuses.Find(ticket.StatusId).Name
                        };
                        db.Histories.Add(history);

Bug Tracker/Bug Tracker/Views/Tickets/Assign.cshtml
@model Bug_Tracker.Models.AssignUsersViewModel

@{
	ViewBag.Title = "Ticket Assignment";
}

<h2>Assign Ticket</h2>

@using (Html.BeginForm("Assign", "Tickets", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
<div>
	<strong>Project Name</strong><br />
	@Model.Ticket.Title
	<br />
	@Html.HiddenFor(model => model.Project.Id, new { })
	<br />
	@Html.ListBox("SelectedUsers", Model.Users, htmlAttributes: new { id = "mySelect" })
	<br />
	<br />
	<button class="btn btn-default" type="submit">Assign to Ticket</button>
</div>
}

<a class="btn btn-default" href="@Url.Action("Index", "Home")">Back to List</a>

Bug Tracker/Bug Tracker/Views/Tickets/Create.cshtml
@model Bug_Tracker.Models.Ticket

@{
    ViewBag.Title = "Create Ticket";
}

<h2>Create Ticket</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <input type="hidden" name="projectId" value="@ViewBag.ProjectId" />

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, 8, 50, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.Updated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Updated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Updated, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.ProjectId, "ProjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.TypeId, "TypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.PriorityId, "PriorityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PriorityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PriorityId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.AuthorUserId, "AuthorUserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorUserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.AssignedToUserId, "AssignedToUserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AssignedToUserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssignedToUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <ul class="list-inline">
                    <li>
                        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Create</button>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Home")" class="btn btn-danger"> <i class="fa fa-ban"></i> Cancel</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
}

Bug Tracker/Bug Tracker/Views/Tickets/Delete.cshtml
@model Bug_Tracker.Models.Ticket

@{
    ViewBag.Title = "Delete Ticket";
}

<h2>Delete Ticket</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AssignedToUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedToUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "Home")
        </div>
    }
</div>

Bug Tracker/Bug Tracker/Views/Tickets/Details.cshtml
@model Bug_Tracker.Models.Ticket

@{
    ViewBag.Title = "Ticket Details";
}

<h2>Ticket Details</h2>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AssignedToUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedToUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", "Home")
</p>